### ISSUE TITLE
Searching for element by repeater not working if using "data-ng-repeat"

### ISSUE THREAD

**Issue by vigor-swe** [ramonvictor/gulp-protractor-qa#10]
In my html, I am using data-ng-repeat instead of ng-repeat

gulp-protractor-qa is unable to find the element unless I change my html to use ng-repeat

**Comment by ramonvictor** [comment]
Hi @vigor-swe! Thanks for spotting the issue. I'm doing my best to publish a new version ASAP.

**Comment by cor03rock** [comment]
Still waiting for the new version. It does happen to me to when using data-ng-model.

**Comment by ramonvictor** [comment]
@cor03rock sorry for taking too long to fix this. I'll try to make a team to help me out on this project. I'll get back to you once we fix this issue.

**Comment by cor03rock** [comment]
Hi @ramonvictor ! Is there any progress regarding this issue? This is really useful to our team. Still hoping that there will be a fix.

**Comment by ramonvictor** [comment]
@vigor-swe, @cor03rock: fix has been published on version [0.1.18](https://www.npmjs.com/package/gulp-protractor-qa). This is the commit that fixes the bug: https://github.com/ramonvictor/gulp-protractor-qa/commit/ff03a15ed35067e92570fcac880e405ba6cde83c#diff-168726dbe96b3ce427e7fedce31bb0bcR128.

**Comment by cor03rock** [comment]
@ramonvictor wow! such a great day to start with this fix! thanks rv! :+1:
