### ISSUE TITLE
Cant watch by.css locator

### ISSUE THREAD

**Issue by cor03rock** [ramonvictor/gulp-protractor-qa#12]
i have a page object that has locators by.model and by.css,
<img width="984" alt="screen shot 2015-10-14 at 10 45 03 am" src="https://cloud.githubusercontent.com/assets/5438128/10473689/c73f8154-7260-11e5-9076-1d766ca18124.png">
 but when i ran the gulp task the result is 
![screen shot 2015-10-14 at 10 46 47 am](https://cloud.githubusercontent.com/assets/5438128/10473697/e4b40a48-7260-11e5-8ea9-9a0bab670380.png)
the by.model locator only is being watch. @ramonvictor any thoughts? thanks in advance!

**Comment by stramel** [comment]
@cor03rock The problem is that the `by.css` regex is missing a `\s*` in the regex. https://github.com/ramonvictor/gulp-protractor-qa/blob/master/lib/util.js#L15

The regex should be `/[b|B]y\.css\(\s*['|"]\[(.+=.+)\]['|"]\)/gi`

**Comment by ramonvictor** [comment]
@cor03rock thanks for spotting the issue. @stramel thanks for your quick fix. 
I'll test it and release another version of the package including this update.

**Comment by ramonvictor** [comment]
@cor03rock: I've just released [v0.1.19](https://www.npmjs.com/package/gulp-protractor-qa) with @stramel's regex fix. :)

**Comment by cor03rock** [comment]
whoooo! thanks guys!
