### ISSUE TITLE
by.css not watching css that starts with "." and "#"

### ISSUE THREAD

**Issue by cor03rock** [ramonvictor/gulp-protractor-qa#14]
<img width="623" alt="screen shot 2015-10-16 at 8 10 40 am" src="https://cloud.githubusercontent.com/assets/5438128/10530779/78e70d28-73dd-11e5-94b3-fd1ad517d375.png">
![screen shot 2015-10-16 at 8 10 26 am](https://cloud.githubusercontent.com/assets/5438128/10530781/7ae54a4a-73dd-11e5-8486-a6baf00258e4.png)

also I think in regex we need to add by.id and by.className. What do you think guys @ramonvictor @stramel ?

**Comment by stramel** [comment]
Definitely, should be able to handle any of the protractor selector apis. Although, the Regex seems a bit off for `by.css`.  I can try to come up with a solid regex for it but it will take a couple days since I'm away from my computer

**Comment by ramonvictor** [comment]
I'll take a look at it this weekend.

**Comment by cor03rock** [comment]
Thanks for checking this out guys! You helped me and my team a lot!

**Comment by ramonvictor** [comment]
Hi @cor03rock, quick heads up, I couldn't fix this issue yet, however I've had a good progress in the big refactoring I'm working on, see [design-refactoring branch](https://github.com/ramonvictor/gulp-protractor-qa/tree/design-refactoring) - still WIP. This new version will address a lot of small issues, including these regex problems. I'm expecting to finish it within this week. I'll let you on whenever the next release is published.

**Comment by cor03rock** [comment]
Hey @ramonvictor, it's ok I can wait. thanks for the really big effort for helping me. I really appreciate it! :+1: :+1: :+1: :+1:

**Comment by stramel** [comment]
Should probably support all the Webdriver APIs since Protractor is built off of it. http://selenium.googlecode.com/git/docs/api/javascript/namespace_webdriver_By.html

**Comment by stramel** [comment]
Added #15 which will allow these to work.

**Comment by stramel** [comment]
@cor03rock This should be closed with the updated refactor that @ramonvictor merged to master.

**Comment by cor03rock** [comment]
Thanks guys! Now waiting for the next release! :+1:
