### ISSUE TITLE
Commented out element selectors still output error

### ISSUE THREAD

**Issue by aripalo** [ramonvictor/gulp-protractor-qa#8]
Element selectors in spec/suite files that are commented out still output errors:
```javascript
//it('should have a list of things', function() {
//  expect(element.all(by.repeater('thing in things')).count()).toBeGreaterThan(4);
//});
```
Which will result in:
```
[gulp] [gulp-protractor-qa] by.repeater('thing in things') at <some-spec-file> not found in view files!
```
... when the view doesn't include that repeater.

Instead protractor-qa should ignore these commented out element selectors.

**Comment by stramel** [comment]
@ramonvictor bump

**Comment by ramonvictor** [comment]
@stramel this is also fixed with new code on master. I was waiting for official `npm publish` in order to close these issues.

**Comment by stramel** [comment]
:+1:

**Comment by ramonvictor** [comment]
[v0.2.0](https://www.npmjs.com/package/gulp-protractor-qa) is out, so closing issue. :smile:
