### ISSUE TITLE
[FEATURE] Run Once

### ISSUE THREAD

**Issue by stramel** [ramonvictor/gulp-protractor-qa#9]
I would like to use this plugin in 2 ways:

1. Run once and no watching of files before my protractor tests are ran manually
2. Continuously, as in development.

I think it would be an easy implementation to make it run once and would be a great feature for this plugin.

**Comment by ramonvictor** [comment]
@stramel, that's a really nice suggestion. 
I'm starting a big code refactoring and I will definitely include your feature while doing that.

Wait my update on this issue within the next couple of days.

**Comment by stramel** [comment]
@ramonvictor What will this refactor focus on?

**Comment by ramonvictor** [comment]
@stramel, there are a few things I want to improve:
- code readability;
- introduce a promise module to avoid too many callbacks;
- code documentation (jsdoc or similar);
- unit test all plugin methods;
- probably change the design pattern;

**Comment by stramel** [comment]
@ramonvictor How is the progress on this going?

**Comment by ramonvictor** [comment]
@stramel to be honest, my last attempt of refactoring failed. I'll find some gurus to help me out in the re-design of this project. Sorry for taking too long.

**Comment by stramel** [comment]
@ramonvictor Hey no problem! I have no room to complain since I haven't helped out. This is an open source project still after all. Thanks for giving it a shot still.

**Comment by ramonvictor** [comment]
@stramel good news is that run-once feature has been included in this refactoring.
When new version is published it's gonna be as easy as:

    protractorQA.init({
        runOnce: true, // optional: when you don't want to watch files changes
        testSrc: 'test/e2e/**/*Spec.js',
        viewSrc: ['index.html', 'partials/*.html']
    });

If you want to test it now, just download latest code from master, run `npm install` and then manually include the package in your project. I'll publish the new npm version soon.

**Comment by stramel** [comment]
Great! I actually don't have anything to test with currently so I will take your word for it. :+1:
